###
POST http://localhost/api/task/test 
Content-Type: application/json

{
    "name":"Test Task" 
}
###

POST http://localhost/api/sign-up
Content-Type: application/json

{
    "name" : "別府奏音",  
    "email" : "s21a1055@bene.fit.ac.jp", 
    "password" : "testPass",
    "checkPassword" : "testPass"
}

###
POST  http://localhost/api/complete-auth
Content-Type: application/json

{
    "id" : 1,
    "code" : "403285"
}

###
POST http://localhost/api/sign-in
Content-Type: application/json

{
    "email" : "s21a1055@bene.fit.ac.jp",
    "password" : "testPass"
}

###
POST http://localhost/api/sign-out
Content-Type: application/json

{
    "id" : 1,
    "accessToken" : "55CABSHFxJ9CkXwjDBOhpqRBfBghLay8E84QukGRcpDNnzWyG2mnt9H0U0eEzMWc",
    "password" : "testPass"
}