###
POST http://localhost/api/task/test 
Content-Type: application/json

{
    "name":"Test Task" 
}
###

POST http://localhost/api/sign-up
Content-Type: application/json

{
    "name" : "別府奏音",  
    "mail" : "s21a1055@bene.fit.ac.jp", 
    "password" : "testPass",
    "checkPassword" : "testPass"
}